gitflow-feature-stash: team-list
f-lab-edu/our-league pull request #1
Opened 2024-04-15 13:10 UTC by minyun02

2024-04-18 13:49 UTC, f-lab-moony requested changes
고생 많으셨습니다!
피드백을 좀 남겨 뒀는데, 확인 후 리뷰 재요청 부탁드려요 ~

2024-04-18 13:49 UTC, f-lab-moony commented on src/main/java/com/minsproject/league/controller/TeamController.java
> +@RequiredArgsConstructor
이 어노테이션을 썼을 때 어떤 문제가 있을 수 있을까요 ?

2024-04-18 13:49 UTC, f-lab-moony commented on src/main/java/com/minsproject/league/controller/TeamController.java
> +    public Response<Page<TeamsResponse>> teamList(Pageable pageable) {
Pageable이나 Page는 저희가 관리하는 클래스들이 아니라서, 별도의 DTO를 만들어주시는게 좋을 것 같아요 ~

2024-04-18 13:49 UTC, f-lab-moony commented on src/main/java/com/minsproject/league/controller/TeamController.java
> +//    @PutMapping("/{teamId}")
쓸모없는 주석은 지워주세요 ~

2024-04-18 13:49 UTC, f-lab-moony commented on src/main/java/com/minsproject/league/controller/TeamController.java
> +    public Response<Void> create(@RequestBody TeamCreateRequest req) {
Response로 굳이 감싸주지 않아도 될 것 같아요 ~

2024-04-18 13:49 UTC, f-lab-moony commented on src/main/java/com/minsproject/league/controller/TeamController.java
> +        teamService.create(TeamCreateDTO.toDto(req));
request에서 DTO로 바꾸시는 이유가 있을까요 ?

2024-04-18 13:49 UTC, f-lab-moony commented on src/main/java/com/minsproject/league/controller/request/TeamCreateRequest.java
> +@AllArgsConstructor
`@AllArgsConstructor` 도 무슨 문제가 있는지 찾아보시면 좋을 것 같아요 ~

2024-04-18 13:49 UTC, f-lab-moony commented on src/main/java/com/minsproject/league/controller/response/Response.java
> +public class Response<T> {
일반적인 성공 응답에선 별로 필요 없는 구조일 것 같아요

오히려 클라이언트측이 구조를 고려하게 돼서 쓰기 불편하지 않을까요 ?

2024-04-18 13:49 UTC, f-lab-moony commented on src/main/java/com/minsproject/league/dto/TeamCreateDTO.java
> +public class TeamCreateDTO {
이 DTO를 따로 만드신 이유가 있을까요 ?

2024-04-18 13:49 UTC, f-lab-moony commented on src/main/java/com/minsproject/league/entity/TeamMembers.java
> +    private Teams teamId;
Teams는 왜 복수형일까요 ?

2024-04-18 13:49 UTC, f-lab-moony commented on src/main/java/com/minsproject/league/entity/Teams.java
> +    private Users creator;
creator나 modifier를 굳이 관계를 맺을 필요는 없어보여요
추가로, created_at이나 modified_at은 필요 없을까요 ?

2024-04-18 13:49 UTC, f-lab-moony commented on src/main/java/com/minsproject/league/service/TeamService.java
> +    Page<TeamsDTO> getTeamList(Pageable pageable);
Pageable을 사용하면 기본적으론 offset방식으로 조회를 할텐데, 게시판처럼 페이지가 지정 된 경우가 아니라 무한스크롤 등에 쓰인다면 more 방식으로 조회하시는게 좋아요. 한번 찾아보시고 적용하면 좋을 것 같습니다 ~

2024-04-18 13:49 UTC, f-lab-moony commented on src/main/java/com/minsproject/league/service/TeamService.java
> +public interface TeamService {
서비스를 굳이 인터페이스로 만드신 이유가 있을까요 ?

2024-04-18 13:49 UTC, f-lab-moony commented on src/main/java/com/minsproject/league/service/TeamServiceImpl.java
> +        Sports sports = sportsRepository.findById(dto.getSportsId()).orElseThrow();
예외를 던질땐 명시적인 타입과 원인을 나타내는 메세지를 명시해주시는게 좋아요

2024-04-19 01:50 UTC, minyun02 commented
넵! 확인하겠습니다 감사합니다.

2024-04-21 07:29 UTC, minyun02 commented on src/main/java/com/minsproject/league/controller/TeamController.java
> +@RequiredArgsConstructor
이 어노테이션을 사용하면 발생하는 문제는 2가지 있습니다.

1. 인스턴스 필드가 Bean으로 등록되었는지 확인할 수 없습니다. 
- 생성자를 명시적으로 작성하면 IDE의 도움을 받아 컴파일 이전에 확인이 가능하지만 Lombok을 사용하면 알 수 없습니다.

2. 인스턴스 필드가 여러 개이라고 타입도 같은 상황에서 필드의 순서가 변경되어도 컴파일 에러가 발생하지 않아 버그를 인지하지 못하는 상황이 생길 수 있다.
- 예를 들어 String name과 String type라는 필드를 가진 Dog라는 클래스가 있을 때
- name과 type의 순서를 type, name으로 변경해도 타입이 같기 때문에 기존 생성자 코드가 컴파일 에러 없이 작동합니다.
- 하지만, 생성된 Dog 클래스의 값은 뒤바뀐 상황이 생기는 겁니다.

2024-04-21 07:30 UTC, minyun02 commented on src/main/java/com/minsproject/league/controller/TeamController.java
> +    public Response<Page<TeamsResponse>> teamList(Pageable pageable) {
넵! 별도의 DTO로 만들겠습니다.

2024-04-21 07:30 UTC, minyun02 commented on src/main/java/com/minsproject/league/controller/TeamController.java
> +//    @PutMapping("/{teamId}")
넵 알겠습니다.

2024-04-21 08:43 UTC, minyun02 commented on src/main/java/com/minsproject/league/controller/TeamController.java
> +        teamService.create(TeamCreateDTO.toDto(req));
presentation 계층에서 서비스 계층을 분리해주기 위해서 controller에서는 TeamCreateRequest를 사용하고 서비스단에서는 TeamCreateDTO를 사용했습니다.

어떤 로직 처리가 없고 데이터도 동일하니까 TeamCreateRequest를 그대로 서비스단으로 넘겨도 괜찮을까요?

2024-04-21 08:45 UTC, minyun02 commented on src/main/java/com/minsproject/league/service/TeamServiceImpl.java
> +        Sports sports = sportsRepository.findById(dto.getSportsId()).orElseThrow();
넵! 타입과 원일 가진 별도의 예외처리로 변경하겠습니다.

2024-04-21 08:46 UTC, minyun02 commented on src/main/java/com/minsproject/league/controller/TeamController.java
> +    public Response<Void> create(@RequestBody TeamCreateRequest req) {
반환 타입이 void는 경우에는 Response로 감싸지 않고 만들어 보겠습니다

2024-04-22 11:58 UTC, f-lab-moony commented on src/main/java/com/minsproject/league/controller/TeamController.java
> +    public Response<Void> create(@RequestBody TeamCreateRequest req) {
반환타입이 void가 아니어도, 성공인 경우에는 굳이 안감싸는게 좋을 것 같아요 ~
예외 발생시에는 에러코드를 정의한다든지 하는 `에러 메세지`에 대한 템플릿을 만드는 건 의미가 있는데, 성공시에는 200에 정의된 응답을 꺼내서 쓸거라 뎁스를 늘려서 얻는 이점이 없어보여요

2024-04-22 11:59 UTC, f-lab-moony commented on src/main/java/com/minsproject/league/controller/TeamController.java
> +        teamService.create(TeamCreateDTO.toDto(req));
네 사실 Request 자체가 컨트롤러와 서비스 사이의 DTO라 굳이 또 만드실 필요 없을 것 같습니다

2024-04-23 15:33 UTC, minyun02 commented on src/main/java/com/minsproject/league/service/TeamService.java
> +public interface TeamService {
습관적으로 인터페이스를 만들었네요..

무니님 리뷰를 보고 서비스단을 인터페이스가 필요한지 조금 찾아보았습니다!

인터페이스와 구현체가 1:1인 경우에는 굳이 추상화가 필요 없을 거 같네요.

2024-05-05 12:44 UTC, minyun02 commented on src/main/java/com/minsproject/league/entity/TeamMembers.java
> +    private Teams teamId;
entity는 테이블을 표현한다고 생각했습니다.

그리고 팀 테이블은 여러 팀의 정보가 모여있으니까 복수형을 사용하는 게 더 맞을 거라고 생각했어요.

2024-05-05 12:46 UTC, minyun02 commented on src/main/java/com/minsproject/league/entity/Teams.java
> +    private Users creator;
멘토링에서 답변해주신거처럼 creator, modifier는 등록자, 수정자의 이름을 받는 방식으로 변경했습니다🫡

created_at, modified_at은 다른 엔티티에도 공통적으로 필요한 항목이라서 BaseEntity에서 정의를하고 상속받는 구조로 변경했습니다.

2024-05-06 04:40 UTC, f-lab-moony approved these changes
고생 많으셨습니다 ~ PR 머지해둘게요~

2024-05-06 04:41 UTC, f-lab-moony commented
이거 제가 머지 권한이 없네요 저 머지 권한 확인좀 부탁드려요 ~

2024-05-06 11:38 UTC, minyun02 commented
> 이거 제가 머지 권한이 없네요 저 머지 권한 확인좀 부탁드려요 ~

assignee로 등록해두었습니다

2024-05-08 13:18 UTC, merged