Feature/#12 매칭 신청
f-lab-edu/our-league pull request #19
Opened 2024-06-29 10:04 UTC by minyun02

## 작업내용
- 매칭을 신청하는 기능 구현

## 리뷰 요구사항
- 멘토링에서 주소 제한을 푸는 방향을 얘기해주셨는데, 개발하고 별도의 PR로 올리겠습니다.
- 매칭 신청에서 유효성을 검사하는 로직을 MatchValidator라는 클래스로 만들었는데 괜찮은 방법인지 궁금하고 해당 클래스를 component로 등록하긴 했지만 유틸 클래스에 더 가깝지 않나라는 고민이 듭니다.

2024-07-02 15:40 UTC, f-lab-moony requested changes
고생많으셨습니다 ~
피드백 확인 후 리뷰 재요청 부탁드려요!

2024-07-02 15:40 UTC, f-lab-moony commented on src/main/java/com/minsproject/league/constant/status/MatchStatus.java
> +@AllArgsConstructor
요 두개는 enum에선 필요없지 않을까요  ?

2024-07-02 15:40 UTC, f-lab-moony commented on src/main/java/com/minsproject/league/dto/PlaceDTO.java
> +    public static Place toEntity(PlaceDTO dto) {
이건 왜 static일까요 ?

2024-07-02 15:40 UTC, f-lab-moony commented on src/main/java/com/minsproject/league/dto/PlaceDTO.java
> +    private Long placeId;
DTO에 id가 필요할까요 ?

2024-07-02 15:40 UTC, f-lab-moony commented on src/main/java/com/minsproject/league/entity/Place.java
> +    public Place(Long placeId) {
id만 가지고 만드는게 어떨 때 필요한걸까요 ?

2024-07-02 15:40 UTC, f-lab-moony commented on src/main/java/com/minsproject/league/entity/TeamMember.java
> +        boolean isOwner = Objects.equals(this.getRole(), TeamMemberRole.OWNER);
요것도 한번 더 빼면 어떨까요 ? 그리고 enum은 기본적으로 싱글톤이라 `==`로 비교해도 될 것 같아요 ~

2024-07-02 15:40 UTC, f-lab-moony commented on src/main/java/com/minsproject/league/validator/MatchValidator.java
> +public class MatchValidator {
validator 따로 쓰는건 괜찮은데, 요거 멘토링시간에 한번 얘기해보시죠!

2024-07-08 11:45 UTC, minyun02 commented on src/main/java/com/minsproject/league/constant/status/MatchStatus.java
> +@AllArgsConstructor
상태 값을 정의한 enum에서 Getter, AllArgsConstructor 어노테이션 제거했습니다.
이 enum 클래스에는 상수 말고는 다른 필드는 없어서 getter가 필요하지 않네요...
다음 PR 반영해서 올리겠습니다.

2024-07-14 12:01 UTC, minyun02 commented on src/main/java/com/minsproject/league/entity/Place.java
> +    public Place(Long placeId) {
매칭에 사용된 매칭 장소가 기존에 있는 매칭 장소면 저장을 위해서 place 엔티티로 만든다라고 생각했었습니다.

현재는 신규 장소인지를 판단해서 신규 장소면 저장하고 기존에 있는 장소면 조회해오는 방식으로 변경했습니다.

다음 PR에 수정한 거 올리겠습니다!

2024-07-14 12:02 UTC, minyun02 commented on src/main/java/com/minsproject/league/dto/PlaceDTO.java
> +    private Long placeId;
매칭을 신청할 때 매칭 장소를 기존에 디비에 저장된 장소들 중에서 선택할 수 있는데, 이 때 placeId가 필요하다고 생각했어요.

2024-07-16 15:48 UTC, merged