로그인, 회원 가입 기능 구현
f-lab-edu/our-league pull request #3
Opened 2024-05-05 12:47 UTC by minyun02

spring security, JWT를 이용해서 로그인 기능을 구현했습니다.

2024-05-06 04:58 UTC, f-lab-moony requested changes
고생 많으셨습니다 ~
피드백 확인 부탁드려요!

2024-05-06 04:58 UTC, f-lab-moony commented on src/main/java/com/minsproject/league/config/filter/JwtTokenFilter.java
> +public class JwtTokenFilter extends OncePerRequestFilter {
JWT를 사용한 이유가 있을까요 ?

2024-05-06 04:58 UTC, f-lab-moony commented on src/main/java/com/minsproject/league/config/filter/JwtTokenFilter.java
> +            if (!JwtTokenUtils.validateToken(token, key)) return;
분기문은 코드블럭을 잡는걸 습관화 해주시는게 좋아요 예기치 못한 동작을 할 위험이 있습니다

2024-05-06 04:58 UTC, f-lab-moony commented on src/main/java/com/minsproject/league/dto/request/TeamModifyRequest.java
> +@AllArgsConstructor
요거 저번에 단점에 대해서 설명 잘 해주셨는데, 최대한 사용 안하는게 좋을 것 같아요 ~

2024-05-06 04:58 UTC, f-lab-moony commented on src/main/java/com/minsproject/league/dto/request/TeamModifyRequest.java
> +    private Long sportsId;
TeamModify인데 왜 sportsId인가요 ?

2024-05-06 04:58 UTC, f-lab-moony commented on src/main/java/com/minsproject/league/entity/Users.java
> +public class Users extends BaseEntity {
Entity는 복수형으로 안쓰는게 좋을 것 같아요 ~

2024-05-06 04:58 UTC, f-lab-moony commented on src/main/java/com/minsproject/league/entity/Users.java
> +    public static Users fromDTO(JoinRequestDTO req, String encodedPassword) {
의존 방향은 바깥에서 안쪽으로만 걸리게 해주세요 ~ 지금 구조라면 DTO가 바뀌면 도메인이 바뀌어야 될 것 같아요

2024-05-07 13:23 UTC, minyun02 commented on src/main/java/com/minsproject/league/dto/request/TeamModifyRequest.java
> +@AllArgsConstructor
습관처럼 넣어뒀네요😅 해당 애너테이션 제거해서 커밋했습니다!

2024-05-07 13:24 UTC, minyun02 commented on src/main/java/com/minsproject/league/config/filter/JwtTokenFilter.java
> +            if (!JwtTokenUtils.validateToken(token, key)) return;
넵! 수정해서 커밋했습니다.

2024-05-07 13:26 UTC, minyun02 commented on src/main/java/com/minsproject/league/dto/request/TeamModifyRequest.java
> +    private Long sportsId;
팀 아이디가 빠진 건 누락입니다.😓

종목 아이디가 포함된 이유는 팀이 가지고 있는 종목이 수정될 걸 염두 해서 넣어뒀는데

종목을 변경 가능하게 해야 하는지 고민해 보겠습니다!

2024-05-07 14:00 UTC, minyun02 commented on src/main/java/com/minsproject/league/entity/Users.java
> +public class Users extends BaseEntity {
저는 테이블 이름을 복수형으로 만들어서 엔티티도 동일한 개념을 적용한 거 같네요.

엔티티가 담고 있는 정보는 인스턴스 하나이니까 단수형이 적합하다고 이해가 되네요!

2024-05-07 14:58 UTC, minyun02 commented on src/main/java/com/minsproject/league/entity/Users.java
> +    public static Users fromDTO(JoinRequestDTO req, String encodedPassword) {
지금처럼 dto를 entity 내부에서 받아서 사용하면 dto의 변경이 entity의 변경으로 이어지겠네요.

Entity 내부의 팩토리 메서드는 제거하고

대신, builder 패턴을 사용해서 서비스단에서 dto를 사용해 entity를 만드는 방식으로 수정했습니다!

2024-05-12 13:51 UTC, f-lab-moony commented on src/main/java/com/minsproject/league/entity/Users.java
> +public class Users extends BaseEntity {
테이블 이름도 마찬가지 개념일 것 같아요 복수형일 이유가 없어보여요

2024-05-12 13:52 UTC, f-lab-moony commented on src/main/java/com/minsproject/league/entity/Users.java
> +    public static Users fromDTO(JoinRequestDTO req, String encodedPassword) {
약간 자주 쓰이는 패턴은 RequestDTO에서는 toEntity로 엔티티를 만들어주고, ResponseDTO에서는 from 같은 팩토리 메서드로 entity를 받아 만들어주는 방식을 많이 사용합니다 ~

2024-05-12 13:53 UTC, f-lab-moony approved these changes
고생 많으셨습니다 ~
이 PR은 일단 머지 해 둘게요~

2024-05-12 13:53 UTC, f-lab-moony commented on src/main/java/com/minsproject/league/config/filter/JwtTokenFilter.java
> +            if (!JwtTokenUtils.validateToken(token, key)) {
👍

2024-05-12 13:53 UTC, merged

2024-05-15 03:07 UTC, minyun02 commented on src/main/java/com/minsproject/league/config/filter/JwtTokenFilter.java
> +public class JwtTokenFilter extends OncePerRequestFilter {
세션 기반 인증을 사용하면 얻을 수 있는 장점 중 하나가 중복 로그인 방지인데 현재 만들고 있는 서비스에서는 여기에대한 필요성을 못 느끼고 있어요.
그리고 서버를 스케일 아웃할 때 JWT는 서버간 동기화가 필요하지 않다라는 장점도 있습니다.
이런 이유로 현재는 토큰 방식 인증을 구현하기로 결정했습니다.

2024-05-15 04:26 UTC, minyun02 commented on src/main/java/com/minsproject/league/entity/Users.java
> +    public static Users fromDTO(JoinRequestDTO req, String encodedPassword) {
그런 식으로 많이 쓰이는군요!

그런데 RequestDTO에서 entity가 만들어져서 나온다는 게 조금 어색하게 느껴지는데 RequestDTO의 역할이라고 봐야 하는 건가요?

2024-05-15 04:35 UTC, minyun02 commented on src/main/java/com/minsproject/league/entity/Users.java
> +    public static Users fromDTO(JoinRequestDTO req, String encodedPassword) {
이거 수정해서 커밋하고 싶은데 이 PR은 이미 머지가 되었으니까 새로 PR을 올리는게 맞겠죠...?