팀 조회 API에 검색 조건 확장을 고려해서 수정
f-lab-edu/our-league pull request #5
Opened 2024-05-12 13:15 UTC by minyun02

수정 사항
- 기존에 검색 조건 기준이 되는 offsetId에서 다른 매개 변수도 받기 위해 dto를 매개변수로 사용

2024-05-12 13:57 UTC, f-lab-moony requested changes
이전 변경사항이랑 합쳐져서 좀 많아보이네요!
근데 검색조건 확장 고려한게 어느부분인지 안보여서 혹시 커밋이 덜 올라온건가 싶어 피드백 남겨둡니다 ~

2024-05-12 13:57 UTC, f-lab-moony commented on src/main/java/com/minsproject/league/controller/TeamController.java
> +        return teamService.getTeamList(searchDTO).stream().map(TeamResponse::fromEntity).toList();
응답으로 만들어주는것도 서비스에서 담당하면 좋을 것 같아요 ~

2024-05-12 13:57 UTC, f-lab-moony commented on src/main/java/com/minsproject/league/service/TeamService.java
> +    public List<Team> getTeamList(TeamSearchDTO searchDTO) {
검색조건 확장을 고려한게 어느부분인걸까요 ?

2024-05-15 03:32 UTC, minyun02 commented on src/main/java/com/minsproject/league/controller/TeamController.java
> +        return teamService.getTeamList(searchDTO).stream().map(TeamResponse::fromEntity).toList();
서비스에서 응답을 만들어주게 수정했습니다!

2024-05-15 03:34 UTC, minyun02 commented on src/main/java/com/minsproject/league/service/TeamService.java
> +    public List<Team> getTeamList(TeamSearchDTO searchDTO) {
기존에는 조회에서 기준이 되는 offsetId만을 받아왔지만

팀 이름이나 운동 종목 같은 검색 조건이 추가될 경우를 생각해서 dto로 변경을 해봤습니다.

2024-05-18 04:52 UTC, minyun02 commented
충돌 발생한 부분이 있어서 수정해서 올렸습니다.

2024-05-26 14:30 UTC, f-lab-moony reviewed
고생 많으셨습니다 ~
코멘트 남겨둔거 확인해주시고 일단 머지 해둘게요 ~

2024-05-26 14:30 UTC, f-lab-moony commented on src/main/java/com/minsproject/league/dto/TeamSearchDTO.java
> +    public static TeamSearchDTO of(Integer pageSize, Long offsetId) {
이 클래스 RequestDto 아닌가요 ? of가 왜 필요한걸까요 ?

2024-05-26 14:30 UTC, f-lab-moony commented on src/main/java/com/minsproject/league/dto/response/TeamResponse.java
> +    public boolean equals(Object o) {
equals&hashcode가 필요한 이유와 직접 만들어주는 이유가 뭘까요 ?

2024-05-26 14:30 UTC, f-lab-moony commented on src/main/java/com/minsproject/league/repository/querydsl/TeamCustomRepositoryImpl.java
> +                .selectFrom(QTeam.team)
static import를 하면 QClass를 드러내지 않을 수 있을 것 같아요

2024-05-26 14:30 UTC, f-lab-moony commented on src/test/groovy/com/minsproject/league/service/TeamServiceTest.groovy
> +    def "TeamSearchDTO의 pageSize가 없으면 10을 기본값으로 잡는다"() {
얘네가 TeamServiceTest에 있는게 맞을까요 ?

2024-05-26 14:30 UTC, f-lab-moony commented on src/test/groovy/com/minsproject/league/service/TeamServiceTest.groovy
> +                Team.builder()
create 메서드를 따로 빼면 더 보기 쉬울 것 같아요

2024-05-26 14:30 UTC, f-lab-moony commented on src/test/groovy/com/minsproject/league/service/TeamServiceTest.groovy
> +                Team.builder()
그리고 그루비라 빌더보단 그냥 생성자 사용하시는게 좀 편하지 않을까 싶습니다

2024-05-26 14:31 UTC, merged

2024-06-01 08:50 UTC, minyun02 commented on src/main/java/com/minsproject/league/dto/TeamSearchDTO.java
> +    public static TeamSearchDTO of(Integer pageSize, Long offsetId) {
테스트에서 필요해서 넣었는데 꼭 of 메서드를 사용할 필요는 없었던거 같아요.. 지금은 멘토님이 알려주신 groovy 문법으로 생성자를 만들어서 테스트하는 방식으로 변경했습니다!

2024-06-01 08:53 UTC, minyun02 commented on src/main/java/com/minsproject/league/dto/response/TeamResponse.java
> +    public boolean equals(Object o) {
팀 목록 조회 테스트코드에서 조회해온 팀 목록과 비교를위해 만들어둔 팀 목록이 같은지를 비교할 때 동등성 검사 문제로 equals&hashcode를 재정의했습니다.

2024-06-01 08:54 UTC, minyun02 commented on src/test/groovy/com/minsproject/league/service/TeamServiceTest.groovy
> +    def "TeamSearchDTO의 pageSize가 없으면 10을 기본값으로 잡는다"() {
teamService보다는 TeamSearchDTO를 테스트하는데 더 어울리겠네요. 위치를 옮겨보겠습니다.!