팀 수정 API 기능 구현
f-lab-edu/our-league pull request #8
Opened 2024-05-29 22:47 UTC by minyun02

2024-05-29 22:58 UTC, minyun02 commented on src/main/java/com/minsproject/league/service/TeamService.java
> +        TeamMember member = teamMemberRepository.findByTeamIdAndUserId(team, UserDTO.toEntity(user)).orElseThrow(() -> new LeagueCustomException(ErrorCode.TEAM_MEMBER_NOT_FOUND));
팀에 가입한 회원인지를 확인하는 데 user entity가 필요해서 userDTO의 id값으로 단순히 entity를 만들어오는 방식인데 괜찮은지 방법일까요?

2024-05-29 22:59 UTC, minyun02 commented on src/test/groovy/com/minsproject/league/service/TeamServiceTest.groovy
> +        teamMemberRepository.findByTeamIdAndUserId(team, user) >> Optional.of(teamMember)
해당 mocking에서 NPE가 발생하는데 어떤 부분을 확인해보면 좋을까요?

2024-06-03 14:03 UTC, f-lab-moony requested changes
고생 많으셨습니다 ~
피드백 확인 부탁드려요!

2024-06-03 14:03 UTC, f-lab-moony commented on src/main/java/com/minsproject/league/controller/TeamController.java
> +        UserDTO principal = (UserDTO) authentication.getPrincipal();
이거 그냥 UserDTO로 바로 받을 수 있지 않나요 ?

2024-06-03 14:03 UTC, f-lab-moony commented on src/main/java/com/minsproject/league/controller/TeamController.java
> +    @ApiResponse(responseCode = "200", description = "팀 수정에 성공하면 수정된 팀 정보를 반환한다")
Response 객체도 문서화가 돼 있을까요 ~?

2024-06-03 14:03 UTC, f-lab-moony commented on src/main/java/com/minsproject/league/controller/TeamController.java
> +    @ApiResponse(responseCode = "200")
요건 굳이 필요 없지 않을까요  ?

2024-06-03 14:03 UTC, f-lab-moony commented on src/main/java/com/minsproject/league/entity/User.java
> +    public static User makeUserForSearch(Long userId) {
이건 왜 이렇게 구현하신걸까요 ?

2024-06-03 14:03 UTC, f-lab-moony commented on src/main/java/com/minsproject/league/dto/request/JoinRequestDTO.java
> +import com.minsproject.league.entity.User;
클래스명에 DTO는 빠져도 될 것 같아요 ~
그리고 지금 클래스들 보면 DTO가 붙은것도 있고 아닌것도 있어요. 이런게 컨벤션인데요, 이런 기조는 맞춰주시는게 가독성에 도움이 됩니다

2024-06-03 14:03 UTC, f-lab-moony commented on src/main/java/com/minsproject/league/dto/request/JoinRequestDTO.java
> +        return User.builder()
이 클래스 지금 UserDTO랑 다른게 뭘까요 ? 쓰임새가 비슷한 것 같아서요

2024-06-03 14:03 UTC, f-lab-moony commented on src/main/java/com/minsproject/league/dto/request/TeamCreateRequest.java
> +                .status(1L)
status 1이 무엇을 의미하나요 ?

2024-06-03 14:03 UTC, f-lab-moony commented on src/main/java/com/minsproject/league/entity/BaseEntity.java
> +    public void softDelete() {
softDelete를 겉으로 명시해줄 필요가 있을까요 ?

그보다 먼저, 이게 BaseEntity에 들어가야 할까요 ? 모든 entity가 soft delete만 사용하진 않을 것 같아서요.

다음으로, removedAt 을 삭제 플래그로 두면 검색도, 보기에도 힘들 것 같습니다. 별도의 boolean 컬럼을 두는게 낫지 않을까요 ?

또, Timestamp를 쓰신 이유가 있을까요? LocalDate / LocalDateTime을 안쓰신 이유가 있을까 싶어 여쭤봅니다 ~

2024-06-03 14:03 UTC, f-lab-moony commented on src/main/java/com/minsproject/league/entity/Team.java
> +    public void modifyTeam(TeamModifyRequest dto, Sports sports, String username) {
sports랑 username은 왜 따로 받는걸까요 ?

2024-06-03 14:03 UTC, f-lab-moony commented on src/main/java/com/minsproject/league/service/TeamService.java
> +        Sports sports = sportsRepository.findById(request.getSportsId()).orElseThrow(() -> new LeagueCustomException(ErrorCode.SPORTS_NOT_FOUND));
SportsService를 만들어서 주입받으면 재사용성을 늘릴 수 있을 것 같아요

2024-06-03 14:03 UTC, f-lab-moony commented on src/main/java/com/minsproject/league/service/TeamService.java
> +        TeamMember member = teamMemberRepository.findByTeamIdAndUserId(team, UserDTO.toEntity(user)).orElseThrow(() -> new LeagueCustomException(ErrorCode.TEAM_MEMBER_NOT_FOUND));
어플리케이션 레벨에서 처리하시는게 나을 것 같습니다 ~

2024-06-03 14:03 UTC, f-lab-moony commented on src/main/java/com/minsproject/league/service/TeamService.java
> +            throw new LeagueCustomException(ErrorCode.DELETING_NOT_ALLOWED);
개인적으로 에러 메세지는 그냥 문자열로 보여주는게 낫다고 생각합니다. 로그로 이슈 트래킹을 할 때 문자열 기준으로 찾고 에러코드가 쓰인곳을 또 찾아야 할거라서요

2024-06-03 14:03 UTC, f-lab-moony commented on src/main/java/com/minsproject/league/service/TeamService.java
> +    private Team getTeamOrThrow(Long teamId) {
Throw는 굳이 메서드명에 안드러내도 되지 않을까요 ?

2024-06-03 14:03 UTC, f-lab-moony commented on src/main/java/com/minsproject/league/service/UserService.java
> +        req.setPasswordEncoded(encoder.encode(req.getPassword()));
요청을 변형해서 entity로 만드는 과정이 조금 어색하게 보이지 않을까요?

2024-06-03 14:03 UTC, f-lab-moony commented on src/test/groovy/com/minsproject/league/service/TeamServiceTest.groovy
> +        teamMemberRepository.findByTeamIdAndUserId(team, user) >> Optional.of(teamMember)
mock에서 NPE가 발생한다는게 무슨뜻일까요 ?

2024-06-10 12:31 UTC, minyun02 commented on src/main/java/com/minsproject/league/service/TeamService.java
> +        TeamMember member = teamMemberRepository.findByTeamIdAndUserId(team, UserDTO.toEntity(user)).orElseThrow(() -> new LeagueCustomException(ErrorCode.TEAM_MEMBER_NOT_FOUND));
팀 멤버를 조회할 때 team, user 엔티티로 조회해오는 방식을 querydsl로 변경했습니다!

2024-06-10 12:53 UTC, minyun02 commented on src/main/java/com/minsproject/league/controller/TeamController.java
> +        UserDTO principal = (UserDTO) authentication.getPrincipal();
그러네요..
AuthenticationPrincipal 어노테이션을 사용해서 바로 받도록 변경했습니다.

2024-06-10 13:08 UTC, minyun02 commented on src/main/java/com/minsproject/league/entity/User.java
> +    public static User makeUserForSearch(Long userId) {
팀 멤버를 등록하는 부분에서 User 엔티티가 필요해서 

User를 조회해오는 대신 UserDTO를 User entity로 바꿔는 방식으로 해봤어요.

User를 조회해오는 방식이 더 괜찮을까요..?

2024-06-10 13:09 UTC, minyun02 commented on src/main/java/com/minsproject/league/dto/request/JoinRequestDTO.java
> +import com.minsproject.league.entity.User;
넵! 클래스명을 맞춰두겠습니다👍

2024-06-10 13:37 UTC, minyun02 commented on src/main/java/com/minsproject/league/dto/request/TeamCreateRequest.java
> +                .status(1L)
처음에 숫자로 상태값을 관리하려고 생각했어요.

지금은 enum을 사용해서 상태를 넣어주는 방식으로 변경했습니다.

Team의 경우 ACCEPTING이면 회원을 받는 상태 PAUSED면 회원을 잠시 받지 않는 상태로 만들었습니다.

2024-06-11 11:53 UTC, minyun02 commented on src/main/java/com/minsproject/league/service/TeamService.java
> +        Sports sports = sportsRepository.findById(request.getSportsId()).orElseThrow(() -> new LeagueCustomException(ErrorCode.SPORTS_NOT_FOUND));
넵! sportsService를 통해서 사용하는 방식으로 바꿨습니다.

2024-06-11 11:59 UTC, minyun02 commented on src/main/java/com/minsproject/league/service/TeamService.java
> +    private Team getTeamOrThrow(Long teamId) {
메서드에서 예외가 발생하니까 메서드명에 그게 드러나면 더 좋지 않을까라는 생각이었는데 꼭 그럴 필요는 없겠군요??

2024-06-11 12:03 UTC, minyun02 commented on src/main/java/com/minsproject/league/service/UserService.java
> +        req.setPasswordEncoded(encoder.encode(req.getPassword()));
builder 패턴을 사용하는거에서 현재는 JoinRequest에서 toEntity 메서드를 통해서 요청을 entity로 만들고 있는데 이게 좀 덜 어색한 방법일까요..?

2024-06-11 12:18 UTC, minyun02 commented on src/main/java/com/minsproject/league/dto/request/JoinRequestDTO.java
> +        return User.builder()
JoinRequest는 회원가입에서만 사용하려고 만든 클래스입니다.

UserDTO는 로그인한 회원 정보를 가지고 있는 클래스입니다.

상황별로 DTO를 나누기보다는 UserDTO 같이 포괄적인 클래스를 사용하는게 좀 더 맞을까요..?

2024-06-11 16:30 UTC, f-lab-moony commented on src/main/java/com/minsproject/league/entity/User.java
> +    public static User makeUserForSearch(Long userId) {
저번시간에 말씀드린 것 처럼 userId를 직접 사용하게 하는게 더 나을 것 같아요 ~

2024-06-11 16:36 UTC, f-lab-moony approved these changes
고생하셨습니다 ~
PR은 머지 해둘게요 ~

2024-06-11 16:36 UTC, f-lab-moony commented on src/main/java/com/minsproject/league/repository/querydsl/TeamMemberCustomRepositoryImpl.java
> +    public Optional<TeamMember> findByTeamIdAndUserId(Long teamId, Long userId) {
👍

2024-06-11 16:36 UTC, f-lab-moony commented on src/main/java/com/minsproject/league/service/SportsService.java
> +    public Sports getSportsById(Long sportsId) {
`@Transactional(readOnly=true)` 붙여주면 좋을 것 같아요 ~

2024-06-11 16:36 UTC, f-lab-moony commented on src/main/java/com/minsproject/league/service/SportsService.java
> +@RequiredArgsConstructor
요거는 한번 고민 해 봐 주세요 ~
서비스같은 경우는 해당 어노테이션의 단점이 잘 나타나지 않을 수 있긴 한데, 다른 DTO객체들과 일관성이 좀 떨어져서 전 NoArgsConstructor 말고는 잘 안쓰는 편입니다

2024-06-11 16:36 UTC, f-lab-moony commented on src/main/java/com/minsproject/league/service/TeamMemberService.java
> +        TeamMember saved = teamMemberRepository.save(TeamMemberDTO.toEntity(team, userInfo, TeamMemberRole.NORMAL, TeamMemberStatus.NORMAL));
👍

2024-06-11 16:36 UTC, merged